#!/usr/bin/env bash

# A git post-receive hook
#
# On main branch only :
# 1. Build and run the containers in the docker compose file
set -ex
## --- Config

deployDir="../deploy"

## --- End Config

while read oldrev newrev refname; do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "main" == "$branch" ]; then
        echo "Hook : deploy to dir $deployDir"
        #we're in a bare repo, so let's checkout this somewhere
        GIT_WORK_TREE=$deployDir git checkout -f main
        cd $deployDir
        cp ../dnt-discord-bot-env .env

        echo "Docker : prune system"
        sudo docker system prune --all --force

        echo "Docker : building and running apps"
        sudo docker compose up --build --detach

        if [ $? -ne 0 ]; then
            echo "Docker : Run failed, aborting"
            exit 1
        fi

    fi
done
